# Generated by Django 5.0.1 on 2024-02-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='habib',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('roll', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('binary_field', models.BinaryField()),
                ('boolean_field', models.BooleanField()),
                ('date_field', models.DateField()),
                ('date_time_field', models.DateTimeField()),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_field', models.DurationField()),
            ],
        ),
    ]
